Default: &defaults
  host: "*4" # any IPv4 host
  port: 3131
  approot: "http://localhost:3131"
  copyright: © 2011 LiloArt.
  #analytics: UA-YOURCODE

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  port: 3011 
  approot: "http://185.44.228.170:3011"
  <<: *defaults